## Code for generating merged tickets & assets csv

In [2]:
import pandas as pd
import numpy as np
from data_generator import df_convert_to_datetimes, merge_tickets_assets

df_tickets = pd.read_csv("data/V_OM_WORK_TASK.csv")
df_assets = pd.read_csv("data/V_OM_WORK_TASK_ASSET.csv")

# Generate merged tickets / assets file
df_tickets_assets = merge_tickets_assets(df_tickets=df_tickets, df_assets=df_assets)

df_tickets_assets["BASELINE_START_LTZ"].head()

/var/folders/y2/tsyh3wpj3mj7zcv4hfd0knl40000gn/T/ipykernel_95208/1481646297.py:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_tickets = pd.read_csv("data/V_OM_WORK_TASK.csv")
/var/folders/y2/tsyh3wpj3mj7zcv4hfd0knl40000gn/T/ipykernel_95208/1481646297.py:6: DtypeWarning: Columns (0,3,4,5,6,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_assets = pd.read_csv("data/V_OM_WORK_TASK_ASSET.csv")

0    2025-09-19 08:24:42.000000
1    2025-09-19 08:30:07.000000
2    2025-09-19 08:30:12.000000
3    2025-09-19 08:30:17.000000
4    2025-09-19 08:30:21.000000
Name: BASELINE_START_LTZ, dtype: object

In [3]:
print(df_tickets_assets['WORK_TASK_ID'].dtype)

object

In [12]:
df_tickets_assets = df_tickets_assets.dropna(subset=['SPACE'])
# df_tickets_assets.head()

print(f"Number of rows with room number attached: {len(df_tickets_assets)}")

df_tickets_assets["SPACE"].head()

Number of rows with room number attached: 125227

0        129
10       206
11       206
12       370
13    105-02
Name: SPACE, dtype: object

In [14]:
# Clean tickets/assets data
df_tickets_assets['WORK_TASK_ID'] = df_tickets_assets['WORK_TASK_ID'].astype('Int64')

# Convert PLANNED_WORKING_DAYS to integer type
df_tickets_assets['PLANNED_WORKING_DAYS'] = df_tickets_assets['PLANNED_WORKING_DAYS'].astype('Int64')

# List of date columns to convert and format
date_columns = [
    'BASELINE_START_LTZ', 'BASELINE_END_LTZ', 'ASSIGNED_DATE_LTZ',
    'PLANNED_START_LTZ', 'PLANNED_END_LTZ', 'PLANNED_FOLLOW_UP_DATE_LTZ',
    'ACTUAL_START_LTZ', 'ACTUAL_END_LTZ', 'CREATE_DATE_LTZ'
]

# Convert and format date columns
for col in date_columns:
    # Ensure column is first converted to datetime, coercing errors
    df_tickets_assets[col] = pd.to_datetime(df_tickets_assets[col], errors='coerce')
    # Format datetime objects to the desired string format, leave NaT as NaN (which will be empty string in CSV)
    df_tickets_assets[col] = df_tickets_assets[col].dt.strftime('%Y-%m-%d %H:%M:%S.%f').replace({np.nan: ''})

In [ ]:
# df_tickets_assets.head()

# output_csv_filename = 'df_merged_tickets_assets.csv'

# # Convert WORK_TASK_ID to integer type before saving
# # Using 'Int64' to allow for potential NaN values if any exist, otherwise 'int' could be used if no NaNs are present.
# df_tickets_assets['WORK_TASK_ID'] = df_tickets_assets['WORK_TASK_ID'].astype('Int64')

# df_tickets_assets.to_csv('df_merged_tickets_assets.csv', index=False)

# print(f"'df_merged_tickets_assets' has been successfully saved to 'df_merged_tickets_assets.csv'")

'df_merged_tickets_assets' has been successfully saved to 'df_merged_tickets_assets.csv'

In [17]:
df_tickets_assets = pd.read_csv("data/df_merged_tickets_assets.csv")

df_tickets_assets['BASELINE_START_LTZ'] = pd.to_datetime(
    df_tickets_assets['BASELINE_START_LTZ'],
    errors='coerce'
)
df_tickets_assets.head()

/var/folders/y2/tsyh3wpj3mj7zcv4hfd0knl40000gn/T/ipykernel_19183/1971072617.py:1: DtypeWarning: Columns (42,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df_tickets_assets = pd.read_csv("data/df_merged_tickets_assets.csv")

,WORK_TASK_ID,WORK_TASK_NAME_ticket,WORK_TASK_STATUS_ticket,RICE_WORK_STATUS,ASSIGNMENT_STATUS,DESCRIPTION,TASK_TYPE,TASK_PRIORITY,REQUEST_CLASS,SERVICE_CLASS,...,CAPITAL_PROJECT_ID,CREATE_DATE_LTZ,WORK_TASK_NAME_asset,WORK_TASK_STATUS_asset,ASSET_ID,ASSET_NAME,ASSET_STATUS,ASSET_PRIMARY_LOCATION,ASSET_PRIMARY_LOCATION_BUILDING,ACCOUNT_STRING
0,1302351,RICE - DEFAULT - Work Task Template - Correcti...,Completed,Work Done,Completed,student at Jones North room 129 has hand foot ...,Corrective,3 - Routine,Custodial Issues,Custodial,...,NaN,2025-09-19 08:24:42.000000,RICE - DEFAULT - Work Task Template - Correcti...,Completed,NaN,NaN,NaN,NaN,NaN,NaN
1,1302352,C10000442-GRB 2nd and 3rd Floor Autoclave Reno...,Closed,Work Done,Completed,NaN,NaN,0 - Admin,Project Management Support,Capital Projects,...,C10000442,2025-09-19 08:30:07.000000,C10000442-GRB 2nd and 3rd Floor Autoclave Reno...,Closed,NaN,NaN,NaN,NaN,NaN,NaN
2,1302353,C10000442-GRB 2nd and 3rd Floor Autoclave Reno...,Closed,Work Done,Completed,NaN,NaN,0 - Admin,Project Management Support,Capital Projects,...,C10000442,2025-09-19 08:30:12.000000,C10000442-GRB 2nd and 3rd Floor Autoclave Reno...,Closed,NaN,NaN,NaN,NaN,NaN,NaN
3,1302354,C10000442-GRB 2nd and 3rd Floor Autoclave Reno...,Closed,Work Done,Completed,NaN,NaN,0 - Admin,Project Management,Capital Projects,...,C10000442,2025-09-19 08:30:17.000000,C10000442-GRB 2nd and 3rd Floor Autoclave Reno...,Closed,NaN,NaN,NaN,NaN,NaN,NaN
4,1302355,C10000442-GRB 2nd and 3rd Floor Autoclave Reno...,Closed,Work Done,Completed,NaN,NaN,0 - Admin,Project Management Support,Capital Projects,...,C10000442,2025-09-19 08:30:21.000000,C10000442-GRB 2nd and 3rd Floor Autoclave Reno...,Closed,NaN,NaN,NaN,NaN,NaN,NaN

## Rules for individual "object"

**All of the following conditions must hold:**
1. Same service class
2. Same request class
3. Same building 

**Future idea:**
1. Same keywords in description (cosine similarity score?)

If the same "object," as defined above, has multiple work tasks in the same 90-day window, then we flag it as a possible persistent issue (repetitive task).

In [16]:
print(df_tickets_assets['BASELINE_START_LTZ'].dtype)

print(df_tickets_assets['BASELINE_START_LTZ'])

object
0         2025-09-19 08:24:42.000000
1         2025-09-19 08:30:07.000000
2         2025-09-19 08:30:12.000000
3         2025-09-19 08:30:17.000000
4         2025-09-19 08:30:21.000000
                     ...
316252    2024-04-08 06:00:00.000000
316253    2024-04-08 06:00:00.000000
316254    2024-04-08 06:00:00.000000
316255    2024-04-08 06:00:00.000000
316256    2024-04-08 06:00:00.000000
Name: BASELINE_START_LTZ, Length: 316257, dtype: object

In [33]:
# Convert to datetime
df_tickets_assets = pd.read_csv("data/df_merged_tickets_assets.csv")

df_tickets_assets['BASELINE_START_LTZ'] = pd.to_datetime(
    df_tickets_assets['BASELINE_START_LTZ'],
    errors='coerce'
)
df_tickets_assets.head()

# Sort the DataFrame by ASSET_ID and BASELINE_START_LTZ for efficient processing
df_merged_assets_sorted = df_tickets_assets.sort_values(by=['SERVICE_CLASS', 'REQUEST_CLASS', 'BUILDING', 'BASELINE_START_LTZ']).reset_index(drop=True)

repeated_tasks_by_object_list = []
ninety_days = pd.Timedelta(days=90)
min_days = pd.Timedelta(days=3) # Set minimum days between each repetitive task to avoid accidental double-submissions by users.

print(ninety_days)

# Filter by corrective first
df_corrective = df_merged_assets_sorted[
    df_merged_assets_sorted['TASK_TYPE'] == 'Corrective' 
]

df_corrective = df_merged_assets_sorted[
    df_merged_assets_sorted['BUILDING'] == 'Duncan College'
]

# FOR TESTING: Remove empty descriptions
df_corrective_2 = df_corrective[
    (df_corrective['DESCRIPTION'].notna()) &
    (df_corrective['DESCRIPTION'].str.strip() != '')
]

print(f"Number of corrective tasks: {len(df_corrective)}")

print_groups = False

# Group by "Object"
group_cols_1 = ['SERVICE_CLASS', 'BUILDING', 'FLOOR', 'SPACE'] # Try tasks with same description

unique_objects = df_corrective_2.groupby(group_cols_1).ngroups
print(f"Number of unique objects (groups): {unique_objects}")

for group_key, group in df_corrective_2.groupby(group_cols_1):
    if len(group) > 1 and print_groups:
        print("new group")
        print(group['DESCRIPTION'].tolist())
    # group_key is a tuple: (SERVICE_CLASS, REQUEST_CLASS, BUILDING)

    for i in range(len(group)):
        current_task = group.iloc[i]
        current_task_time = current_task['BASELINE_START_LTZ']

        # Check subsequent tasks for repetition within 90 days
        subsequent_tasks = group.iloc[i+1:]
        for j in range(len(subsequent_tasks)):
            other_task = subsequent_tasks.iloc[j]
            other_task_time = other_task['BASELINE_START_LTZ']

            time_difference = other_task_time - current_task_time

            if pd.isna(time_difference):  # Skip if time_difference is NaT
                continue

            if time_difference <= ninety_days and time_difference >= min_days:
                repeated_tasks_by_object_list.append(current_task.to_dict())
                break
            elif time_difference > ninety_days:
                break



# Create a new DataFrame from the identified repeated tasks
df_tickets_filtered_by_object = pd.DataFrame(repeated_tasks_by_object_list)

print(f"Found {len(df_tickets_filtered_by_object)} repetitive tasks by object within {ninety_days.days} days.")

/var/folders/y2/tsyh3wpj3mj7zcv4hfd0knl40000gn/T/ipykernel_19183/153806522.py:2: DtypeWarning: Columns (42,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df_tickets_assets = pd.read_csv("data/df_merged_tickets_assets.csv")

90 days 00:00:00
Number of corrective tasks: 6630
Number of unique objects (groups): 789
Found 137 repetitive tasks by object within 90 days.

In [34]:
import matplotlib.pyplot as plt

group_sizes = df_corrective_2.groupby(group_cols_1).size()

size_distribution = group_sizes.value_counts().sort_index()
size_distribution.index.name = 'Group Size'
size_distribution.name = 'Number of Objects'

print(size_distribution.to_string())

Group Size
1     531
2     147
3      51
4      29
5       9
6       9
7       7
8       2
9       1
10      1
11      1
16      1

# Total Corrective Tasks: 100624

## 90 days:
- Using cols_1 grouping: 58641 repetitive tasks
- Using cols_2 grouping: 55400 repetitive tasks
- Using cols_3 grouping: 11692 repetitive tasks

## 45 days:
- Using cols_1 grouping: 
- Using cols_2 grouping: 45146
- Using cols_3 grouping: 8845

In [42]:
# if not df_tickets_filtered_by_object.empty:
#     print("First 5 rows of df_tickets_filtered_by_object:")

rows = df_tickets_filtered_by_object.to_dict('records')

for j in range(len(rows)):
    print(f"Work ID: {rows[j]['WORK_TASK_ID']} Description: {rows[j]['DESCRIPTION']}")   # first column of row j

Work ID: 1300437 Description: Automatic door not working well. Also the double wooden doors form the exterior to commons are acting up
Work ID: 1313529 Description: The push button to the ADA door opener the battery came loose to the mechanism we need this operational ASAP please it open the Access doors remotely when we have a patron needs to cross the bridge to get to the administration side. Please see Rudy I have the push button also we need it to be installed on the desk.
Work ID: 1303150 Description: ***IGNORE. TRIRIGA ADMIN TESTING FOR NEW ZONING PROJECT. DELETE OR CLOSE IF NEEDED*** Zone 2 TEST
Work ID: 1196427 Description: Front door ADA button is not working . Contact Center : Alexander Rodriguez
Work ID: 1283857 Description: Student lost key
Work ID: 1220810 Description: Please grant student access to MEB 241.
Work ID: 1220811 Description: Please grant student access to MEB 241. Thank you!
Work ID: 1276132 Description: The card readers located within the COB elevators are malfunctioning, leading passengers to feel as though they are trapped inside. Please repair as soon as possible.
Work ID: 1313859 Description: The cardreader is not working. Contact Center : James Chappell
Work ID: 1151729 Description: Need to replace the core.
Work ID: 1151733 Description: Need to replace the core.
Work ID: 1200767 Description: Latch on double doors does not function properly.  Door will not sty closed.
Work ID: 1309764 Description: 1) Garage door is not always closing, malfunctioning 2) Living Room Sliding Door is stuck, malfunctioning
Work ID: 1274773 Description: Label Assets in Brockman Physics Contact Center :
Work ID: 1234203 Description: Service by Vendor: Cougar Sales to troubleshoot and repair sewer sump pump system. Related work task #1234011
Work ID: 1298960 Description: Contractor to replace split systems for electrical KVA room
Work ID: 1298960 Description: Contractor to replace split systems for electrical KVA room
Work ID: 1298960 Description: Contractor to replace split systems for electrical KVA room
Work ID: 1313769 Description: Investigate the freeze stat on both AHUs
Work ID: 1287133 Description: Fume Hood in 270 is not making any audible or visible signs that emergency purge is working.
Work ID: 1287135 Description: Fume Hood in 270 is not making any audible or visible signs that emergency purge is working.
Work ID: 1295492 Description: Fume hoods have low exhaust
Work ID: 1295492 Description: Fume hoods have low exhaust
Work ID: 1295489 Description: Units have low exhaust
Work ID: 1281590 Description: Fume hoods failed due to emergency purge failure.
Work ID: 1281547 Description: Fume-Hood failed preventative maintenance due to emergency purge failure.
Work ID: 1281547 Description: Fume-Hood failed preventative maintenance due to emergency purge failure.
Work ID: 1281547 Description: Fume-Hood failed preventative maintenance due to emergency purge failure.
Work ID: 1281547 Description: Fume-Hood failed preventative maintenance due to emergency purge failure.
Work ID: 1281550 Description: Fume-Hood failed preventative maintenance due to emergency purge failure. FH-02-013 is found in e228. There is no asset sticker on the unit. It is the unit furthest on the left side of the classroom.
Work ID: 1281552 Description: Fume-Hood failed preventative maintenance due to emergency purge failure. Fume-Hood in w311 failed, has old asset tag #101809.
Work ID: 1281552 Description: Fume-Hood failed preventative maintenance due to emergency purge failure. Fume-Hood in w311 failed, has old asset tag #101809.
Work ID: 1281545 Description: Fume-hood failed preventative maintenance  due to emergency purge failure.
Work ID: 1281545 Description: Fume-hood failed preventative maintenance  due to emergency purge failure.
Work ID: 1281545 Description: Fume-hood failed preventative maintenance  due to emergency purge failure.
Work ID: 1281545 Description: Fume-hood failed preventative maintenance  due to emergency purge failure.
Work ID: 1281545 Description: Fume-hood failed preventative maintenance  due to emergency purge failure.
Work ID: 1281545 Description: Fume-hood failed preventative maintenance  due to emergency purge failure.
Work ID: 1265335 Description: Investigate differential offset. Correct the imbalance
Work ID: 1265336 Description: Investigate differential offset. Correct the imbalance
Work ID: 1265337 Description: Investigate differential offset. Correct the imbalance
Work ID: 1265338 Description: Investigate differential offset. Correct the imbalance
Work ID: 1265339 Description: Investigate differential offset. Correct the imbalance
Work ID: 1265340 Description: Investigate differential offset. Correct the imbalance
Work ID: 1283499 Description: Fume hood units have issues with them. Either no having enough exhaust or purge fails. Room 122 has a fume hood also but is not listed.
Work ID: 1283499 Description: Fume hood units have issues with them. Either no having enough exhaust or purge fails. Room 122 has a fume hood also but is not listed.
Work ID: 1283502 Description: Fume hoods have issues. Issues include not having enough exhaust or purge failing.
Work ID: 1283502 Description: Fume hoods have issues. Issues include not having enough exhaust or purge failing.
Work ID: 1283502 Description: Fume hoods have issues. Issues include not having enough exhaust or purge failing.
Work ID: 1283570 Description: Fume Hood in Room 200 with serial number 120783-13.1-03 failed because the unit was not responding to the purge button. Units 133 FH 03 003 & 004 in 306 failed because the fume hood controller is reading a high number with little exhaust. All units are new, may need minor adjustments.
Work ID: 1213137 Description: CW temps. for chillers #5 & #6 reading 20+ deg F less than actual temp. on the HMI's
Work ID: 1286913 Description: Change Chillers 1-4 flow (chw & cw) refresh rate.  Preferably have the match chillers 5&6.
Work ID: 1286913 Description: Change Chillers 1-4 flow (chw & cw) refresh rate.  Preferably have the match chillers 5&6.
Work ID: 1286913 Description: Change Chillers 1-4 flow (chw & cw) refresh rate.  Preferably have the match chillers 5&6.
Work ID: 1226628 Description: Check chw return x-mitters for Chillers #1 & #2.  They should be closer in temp. as both are coming from the same pipe.  This skews the tonnage reading a bit
Work ID: 1200160 Description: Can't get boilers 1 and 2 to restart.
Work ID: 1275741 Description: PCV-SSTM-01 & 02 not responding to commands in auto or manual
Work ID: 1273753 Description: Accumulator pumps #1 & #2 need to have orifices installed in their recirc. lines
Work ID: 1311198 Description: Please check the strainers on the Accumulator Pumps #1 and #2.
Work ID: 1303635 Description: Fix the steam trap with the tag number 0237. Contact Center : Harvey Willis
Work ID: 1228215 Description: Perform semi-annual PM on cooling towers 1,2,3,4, and 5.
Work ID: 1228215 Description: Perform semi-annual PM on cooling towers 1,2,3,4, and 5.
Work ID: 1228215 Description: Perform semi-annual PM on cooling towers 1,2,3,4, and 5.
Work ID: 1228215 Description: Perform semi-annual PM on cooling towers 1,2,3,4, and 5.
Work ID: 1206093 Description: President's office is too cold. Contact Center : Hope Gatliff
Work ID: 1206705 Description: President's office is too cold. Contact Center : Hope Gatliff
Work ID: 1313341 Description: Good Morning, the third floor has been freezing, and during this cold weather, we have individuals who are bundled up in coats and blankets. This has been ongoing, and we've placed several work orders but haven't received a resolution. It is about 64 degrees on our floor.  Could this please be checked on, thank you
Work ID: 1311373 Description: Please raise the temperature a few degrees in COB 430.  Contact Center : Eugen Radulescu
Work ID: 1311350 Description: Please raise the temperature in the lobby Contact Center : Dawn Lofton
Work ID: 1104971 Description: Too cold
Work ID: 1105212 Description: Very cold
Work ID: 1277906 Description: The temperature in 133B is way too cold to a point that everyone in our office has to wear multiple jackets and a heated blanket to cover our legs so that we don't catch a cold. If someone could adjust the temperature of the AC higher to around 73-75F (not sure what the current temperature is set to), we'd greatly appreciate that! Thank you for your time and effort!
Work ID: 1313356 Description: The individual office is too cold inside. Please raise the temperature. Thank you!
Work ID: 1313435 Description: The suite is too cold. Please raise the temperature. Thank you!
Work ID: 1311716 Description: Too cold, bump up a few degrees. Contact Center : Martha Hernandez Galvan
Work ID: 1312471 Description: Very cold in room B-35. Contact Center : Martha Hernandez Galvan
Work ID: 1145183 Description: Raise temperature set point 4 degrees. We have some plants rooms that are out of the temperature range we need for our plants.  Rooms E308E and E308G (marked as Bartel plant rooms 1 and 2) are currently around 18C, and we need them closer to 22C.
Work ID: 1246245 Description: Too cold in room W201. Contact Center : Juan Sanchez
Work ID: 1306178 Description: All of the rooms in the Herzstein Hall 105 Suite are entirely too cold.  Please take the temperature down several degrees. We are all freezing in there!
Work ID: 1306179 Description: All of the rooms in the Herzstein Hall 105 Suite are entirely too cold.  Please take the temperature down several degrees. We are all freezing in there!
Work ID: 1306180 Description: All of the rooms in the Herzstein Hall 105 Suite are entirely too cold.  Please take the temperature down several degrees. We are all freezing in there!
Work ID: 1163440 Description: currently 72 and would like it to be 74/75
Work ID: 1163442 Description: currently 72 and would like it to be 74/75
Work ID: 1163443 Description: currently 72 and would like it to be 74/75
Work ID: 1313216 Description: Temperature is currently 63 degrees. Raise to 72 degrees. Whole hallway and all offices on that side are too cold. Per Tegan Gutierrez x3726 <tegang@rice.edu>
Work ID: 1313343 Description: My office is still too cold. It was 60 yesterday and is now registering 66, but the setting is 72.
Work ID: 1093475 Description: room is too cold
Work ID: 1057138 Description: Office is too cold. Contact Center : Eileen Singleton
Work ID: 1168673 Description: The lab is 66 F right now. Could you adjust the temperature to 72 F?
Work ID: 1168674 Description: The lab is 66 F right now. Could you adjust the temperature to 72 F?
Work ID: 1313468 Description: MDA HW ALM1 on Desigo. Please check!
Work ID: 1313420 Description: Please raise temp. Too cold in welcome center offices
Work ID: 1313339 Description: Very cold in room 322. A/C unit may not be working. Contact Center : Bryan Miller
Work ID: 1194120 Description: Too cold in office 234,Currently at 63 degrees.  Contact Center : Israel Ramirez
Work ID: 1313101 Description: Please adjust the temperature in Kraft Hal 4th floor. it is freezing inside the building and there is cold air blowing in the AC. Thanks!
Work ID: 1313142 Description: Please raise the temperature in KRF 200. Contact Center : Christie Bradow
Work ID: 1311666 Description: per Robbie at Local Foods at 9:10am, make Brochstein warmer.  Thank you
Work ID: 1119677 Description:  Can we get someone to fix ac at Duncan PDR. The ambient temperature is hot, students are having a meeting.  Contact Center : Olivia Waldron
Work ID: 1313107 Description: I requested that the temp be lowered for an event on Saturday, but today it is very cold in the whole building (Cannady Hall) please bring the temp up a few degrees. Thank you.
Work ID: 1313369 Description: The whole building is too cold. URGENT Contact Center : Bryan Miller
Work ID: 1043934 Description: For controls, Please lower the A/C at Seibel servery. Kitchen is good, servery is hot. Currently reading 80F    Contact Center : Olivia Waldron
Work ID: 1276796 Description: Please lower the temperature in the office. Contact Center : Linda Marquez
Work ID: 1283579 Description: On 5/15/2025, need AC on in McMurtry Auditorium (1055), Martel Hall (1057), and Jamail Conference Room (1049), from 6:00 AM to 9:00 PM.  This is for ASM Houston Chapter Technical Seminar.
Work ID: 1283580 Description: On 5/15/2025, need AC on in McMurtry Auditorium (1055), Martel Hall (1057), and Jamail Conference Room (1049), from 6:00 AM to 9:00 PM.  This is for ASM Houston Chapter Technical Seminar.
Work ID: 1282030 Description: On April 29, ensure air conditioning is on from 6:00 AM to 8:00 PM for scheduled event
Work ID: 1282040 Description: On May 15, ensure air conditioning is on from 6:00 AM to 8:00 PM for scheduled event
Work ID: 1043728 Description: MCM 5B suite hallway AC is not cooling - send this to controls please Contact Center : Bradley Thacker
Work ID: 1295596 Description: Every morning, the AC doesn't turn on until we request it to be cooler. It has been happening since 6/23/25. An employee would let me know around 8:30 every time she is in office.  Is there a way to adjust when the AC turns on?   Thank you.
Work ID: 1135209 Description: Humid. Please, only a minor adjustment!
Work ID: 1135210 Description: Humid. Please, only a minor adjustment!
Work ID: 1311320 Description: The air is not on. It is quite hot and musty and stale.
Work ID: 1311328 Description: The air is not on. It is quite hot and musty and stale.
Work ID: 1191480 Description: Too Hot Contact Center : Anzilla Gilmore
Work ID: 1196652 Description: Too hot, need to adjust by 2 or 3 degrees cooler. Contact Center : Patricia Aviles
Work ID: 1305956 Description: It's pretty stuffy in my office. If the temperature could be turned down, that would be great! Thank you!
Work ID: 1311162 Description: The temperature in the suite is currently too high. Please bring it down to a more comfortable level. Thank you!
Work ID: 1311364 Description: too warm, can't adjust
Work ID: 1191592 Description: Too Hot Contact Center : Christina Keefe
Work ID: 1311700 Description: The classroom is blazing hot and there don't seem to be controls to adjust it.
Work ID: 1306341 Description: There will be an event in our building in a few rooms and we need the AC to be colder.
Work ID: 1313895 Description: We have an event in this room this evening from 5:30-7:30 with 125 guests. So it will get hot. If you could please set the temperature to be 70 degrees that would be great!
Work ID: 1313227 Description: Classroom 214 is very warm. It is registering at 70 in Desigo, but I went into the room and it is easily 75. Please adjust as soon as possible for the class in there right now.
Work ID: 1313273 Description: Classroom 317 is registering as 76 but is set at 70. Please adjust this temperature as soon as possible for the class currently in that room.
Work ID: 1313331 Description: The room is too warm Contact Center : Micah Shipman
Work ID: 1313371 Description: The temperature needs to be lowered. Contact Center : Deanna Golden
Work ID: 1040923 Description: Too Hot.
Work ID: 1041265 Description: Too hot in room 115.
Work ID: 1195870 Description: Secondary chill calling high level alarm.  Contact Center : Donald Armstrong
Work ID: 1052290 Description: Room is too hot as the sun is shining into the room. Occupants have the blinds closed. Contact Center : Gerald Mixon
Work ID: 1196965 Description: TOO HOT
Work ID: 1312668 Description: A lot of warm bodies in here. Would appreciate the air conditioner turning on. Thank you.
Work ID: 1277672 Description: Over the past few days the network closet has been getting hotter.  I will also put in a ticket for the other floors
Work ID: 1277673 Description: Over the past few days the network closet has been getting hotter.  I will also put in a ticket for the other floors
Work ID: 1041708 Description: Vendor in Sammy's now. It is very very hot. Kitchen & serving area. entire space.  Contact Center : Olivia Waldron
Work ID: 1236042 Description: Kaitlin Sanders 214-856-9612 outside bike rack (white ) Contact Center : Kaitlin Sanders
Work ID: 1201179 Description: Pre-Event Preparation Artic Freeze Contact Center : Allysia Kizzee
Work ID: 1201174 Description: Pre-Event Preparation Artic Freeze Contact Center : Allysia Kizzee
Work ID: 1201177 Description: Pre-Event Preparation Artic Freeze Contact Center : Allysia Kizzee
Work ID: 1313515 Description: Our gate  Lock cylinder came out While unlocking the gate walk in gate to the facility, the entire lock cylinder came out when the key was removed.  The lock cylinder is on the inside of the track.  Can we have this fixed ASAP so we are able to lock it up at the end of the day
Work ID: 1193586 Description: Need to have the traffic cone removed from Willy statue's head.   Contact Center : DISPATCH Contact
Work ID: 1311885 Description: We need all of the pool deck and outdoor basketball to be pressure wash thank you
Work ID: 1208116 Description: Remove cones from Willy's statue.  Contact Center : DISPATCH Contact
Work ID: 1229695 Description: Can you have someone blow away the leaves from the gas and diesel containment tanks out in the vehicle repair shop. See Will for details and exact location, Contact Center : Leonel Rivera
Work ID: 1191286 Description: Roof leak
Work ID: 1191287 Description: Roof leak
Work ID: 1255429 Description: Check for any roof damage due to Hurricane Beryl. Contact Center : David Garcia
Work ID: 1298251 Description: Request for lofting supplies
Work ID: 1298704 Description: Fan does not turn on in room
Work ID: 1310885 Description: A discussed with Benny, please install plastic or sheetrock to cover the ceiling prior to classes commencing Monday, January 11.
Work ID: 1310886 Description: A discussed with Benny, please install plastic or sheetrock to cover the ceiling prior to classes commencing Monday, January 11.
Work ID: 1295384 Description: The door needs to be readjusted it will not latch
Work ID: 1258638 Description: The door makes a loud metal scraping noise when opened and closed
Work ID: 1276263 Description: We did the FCU PM's for Baker Hall (Bld 150) and found the 2 units in the stairwells are not fully serviceable due to the side mounted drywall enclosure around them. it only allows us to barely change the filter but reaching the access door to visually inspect the coil or fan is extremely tight. If the unit has a blown motor it would not be reachable to replace and would require access cut in anyway. I asked Jonathan what he does in cases like this and he recommended another access panel.  In looking at the structure I think it would leave 2 options but I wanted to get your opinion as well in case you have an easier idea.  1. Current access panel upsized to a larger door so tech can climb over/under beams to reach 2. Secondary access panel installed on side, but may require some framing to be gutted.  The units are in stair A and B EQ-1021755 150-FCU-02-001 Fan Coil Unit #4 (EQ0100622) \Locations\Rice\James A. Baker III Hall\02\STAIR-A EQ-1021756 150-FCU-02-002 Fan Coil Unit #5 (EQ0100
Work ID: 1306654 Description: Cohen house men's and women's restroom has two fan coils that are difficult to gain access to servicing for generic filters, condensate pan clearing and general maintenance. Require installation of drywall access panel to properly maintain and service units to extend life beyond run to failure.
Work ID: 1267953 Description: Students often report "thick and musty air" and note that it is always "too hot". (FSC, This is for controls)
Work ID: 1045918 Description: Mass Timber Grant Project Work Order for Faten Tayeh, Project Manager. Contact Center : Olivia Waldron
Work ID: 1240364 Description: Carpenters to install 7 Menstrual Products dispensers in Anderson Biology, O'Connor, Brockman Hall for Physics, BRC, See Hannes for details. Non-billable.

In [22]:
if not df_tickets_filtered_by_object.empty:
    print("First 5 rows of df_tickets_filtered_by_asset:")

df_tickets_filtered_by_object.head()

First 5 rows of df_tickets_filtered_by_asset:

,WORK_TASK_ID,WORK_TASK_NAME_ticket,WORK_TASK_STATUS_ticket,RICE_WORK_STATUS,ASSIGNMENT_STATUS,DESCRIPTION,TASK_TYPE,TASK_PRIORITY,REQUEST_CLASS,SERVICE_CLASS,...,CAPITAL_PROJECT_ID,CREATE_DATE_LTZ,WORK_TASK_NAME_asset,WORK_TASK_STATUS_asset,ASSET_ID,ASSET_NAME,ASSET_STATUS,ASSET_PRIMARY_LOCATION,ASSET_PRIMARY_LOCATION_BUILDING,ACCOUNT_STRING
0,1228322,RICE - DEFAULT - Work Task Template - Correcti...,Closed,Work Done,Completed,West entry into Foyer: North ADA door (Door 5)...,Corrective,2 - Urgent,ADA Door Not Working,Access Control,...,NaN,2023-10-13 14:20:41.000000,RICE - DEFAULT - Work Task Template - Correcti...,Closed,NaN,NaN,NaN,NaN,NaN,NaN
1,1232174,RICE - DEFAULT - Work Task Template - Correcti...,Closed,Work Done,Completed,Exterior wave-to-open ADA door is not respondi...,Corrective,2 - Urgent,ADA Door Not Working,Access Control,...,NaN,2023-12-11 09:04:33.000000,RICE - DEFAULT - Work Task Template - Correcti...,Closed,NaN,NaN,NaN,NaN,NaN,NaN
2,1236657,RICE - DEFAULT - Work Task Template - Correcti...,Closed,Work Done,Completed,South wave to open on Grand Foyer exterior is ...,Corrective,2 - Urgent,ADA Door Not Working,Access Control,...,NaN,2024-03-01 18:17:38.000000,RICE - DEFAULT - Work Task Template - Correcti...,Closed,NaN,NaN,NaN,NaN,NaN,NaN
3,1275736,RICE - DEFAULT - Work Task Template - Correcti...,Completed,Work Done,Completed,Wave-to-open on south side of west entry (by D...,Corrective,2 - Urgent,ADA Door Not Working,Access Control,...,NaN,2025-02-21 08:44:57.000000,RICE - DEFAULT - Work Task Template - Correcti...,Completed,NaN,NaN,NaN,NaN,NaN,NaN
4,1281622,RICE - DEFAULT - Work Task Template - Correcti...,Completed,Work Done,Completed,North exterior wave-to-open is not working (on...,Corrective,2 - Urgent,ADA Door Not Working,Access Control,...,NaN,2025-04-17 11:38:00.000000,RICE - DEFAULT - Work Task Template - Correcti...,Completed,NaN,NaN,NaN,NaN,NaN,NaN